#development:
#  adapter: postgresql
#  encoding: unicode
#  database: family-development
#  pool: 5
#  username: payton

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: kokopelli
  pool: 5
  username: root
  password: U8P%9;Wnof
  socket: /var/run/mysqld/mysqld.sock